hmrc/income-tax-state-benefits

- app/connectors/IFConnector.scala
- app/connectors/IntegrationFrameworkConnector.scala
- app/models/api/CustomerAddedStateBenefit.scala
- app/models/api/StateBenefit.scala
- it/connectors/IntegrationFrameworkConnectorISpec.scala
- test/connectors/IFConnectorSpec.scala
- test/models/api/AllStateBenefitsDataSpec.scala
- test/models/api/StateBenefitSpec.scala
- test/models/api/StateBenefitsDataSpec.scala
- test/support/builders/api/CustomerAddedStateBenefitBuilder.scala
- test/support/builders/api/StateBenefitBuilder.scala
- test/support/stubs/AppConfigStub.scala
[SASS-3373](https://jira.tools.tax.service.gov.uk/browse/SASS-3373)
> SASS-3373 - Connect State Benefits to IF using GET API.

- app/controllers/GetStateBenefitsController.scala
- app/services/StateBenefitsService.scala
- conf/app.routes
- conf/prod.routes
- project/AppDependencies.scala
- test/controllers/GetStateBenefitsControllerSpec.scala
- test/services/StateBenefitsServiceSpec.scala
- test/support/mocks/MockAuthorisedAction.scala
- test/support/mocks/MockIntegrationFrameworkConnector.scala
- test/support/mocks/MockStateBenefitsService.scala
- test/support/providers/ResultBodyConsumerProvider.scala
[SASS-3372](https://jira.tools.tax.service.gov.uk/browse/SASS-3372)
> SASS-3372 - Add State Benefits to the overview page.

- app/controllers/UserSessionDataController.scala
- app/models/api/BenefitType.scala
- app/models/mongo/ClaimCYAModel.scala
- app/models/mongo/StateBenefitsUserData.scala
- app/services/StateBenefitsService.scala
- conf/app.routes
- test/controllers/GetStateBenefitsControllerSpec.scala
- test/controllers/GetUserPriorDataControllerSpec.scala
- test/controllers/UserSessionDataControllerSpec.scala
- test/models/api/BenefitTypeSpec.scala
- test/services/StateBenefitsServiceSpec.scala
- test/support/ControllerUnitTest.scala
- test/support/builders/api/AllStateBenefitsDataBuilder.scala
- test/support/builders/api/CustomerAddedStateBenefitsDataBuilder.scala
- test/support/builders/api/StateBenefitsDataBuilder.scala
- test/support/builders/mongo/ClaimCYAModelBuilder.scala
- test/support/builders/mongo/StateBenefitsUserDataBuilder.scala
- test/support/mocks/MockAuthorisedAction.scala
- test/support/mocks/MockStateBenefitsService.scala
[SASS-3591](https://jira.tools.tax.service.gov.uk/browse/SASS-3591)
> SASS-3591 - Create 'When did you start getting JSA?' page

- app/connectors/responses/GetIncomeTaxUserDataResponse.scala
- test/connectors/responses/GetIncomeTaxUserDataResponseSpec.scala
> SASS-3824 - [FIX] Handles NO_CONTENT response from Submisssion BE.

- .github/PULL_REQUEST_TEMPLATE.md
> Updates checklist for PR reviews.

- app/repositories/StateBenefitsUserDataRepositoryImpl.scala
> Replaces index if exists.

- app/controllers/StateBenefitsController.scala
- app/controllers/UserSessionDataController.scala
- conf/app.routes
- test/controllers/StateBenefitsControllerSpec.scala
- test/controllers/UserSessionDataControllerSpec.scala
[SASS-3694](https://jira.tools.tax.service.gov.uk/browse/SASS-3694)
> [SASS-3694] Added dummy endpoint for remove claim

- app/controllers/UserSessionDataController.scala
- app/repositories/Repository.scala
- app/repositories/StateBenefitsUserDataIndexes.scala
- app/repositories/StateBenefitsUserDataRepositoryImpl.scala
- app/services/StateBenefitsService.scala
- app/utils/PagerDutyHelper.scala
- it/repositories/StateBenefitsUserDataRepositoryImplISpec.scala
- test/services/StateBenefitsServiceSpec.scala
- test/support/mocks/MockStateBenefitsUserDataRepository.scala
[SASS-3905](https://jira.tools.tax.service.gov.uk/browse/SASS-3905)
> SASS-3905 - JSA Implement 'view' link functionality.

- app/connectors/IntegrationFrameworkConnector.scala
- app/connectors/responses/AddStateBenefitResponse.scala
- app/models/api/AddStateBenefit.scala
- app/services/PagerDutyLoggerService.scala
- conf/application.conf
- it/connectors/IntegrationFrameworkConnectorISpec.scala
- it/support/stubs/WireMockStubs.scala
- test/connectors/responses/AddStateBenefitResponseSpec.scala
- test/support/builders/api/AddStateBenefitBuilder.scala
[SASS-4017](https://jira.tools.tax.service.gov.uk/browse/SASS-4017)
> SASS-4017 - Implement Add State Benefits API.

- app/models/api/AllStateBenefitsData.scala
- test/connectors/responses/GetIncomeTaxUserDataResponseSpec.scala
- test/connectors/responses/GetStateBenefitsResponseSpec.scala
- test/models/api/AllStateBenefitsDataSpec.scala
- test/support/builders/api/AllStateBenefitsDataBuilder.scala
> [Fix] Api model change.

- project/AppDependencies.scala
> Upgrade Mongo play and backend play dependencies

- README.md
- project/build.properties
Update README.md file for State Benefits BE
[SASS-4100](https://jira.tools.tax.service.gov.uk/browse/SASS-4100)
> SASS-4100 - Update README.md file for State Benefits BE

- app/connectors/IntegrationFrameworkConnector.scala
- conf/application.conf
- it/connectors/IntegrationFrameworkConnectorISpec.scala
- project/plugins.sbt
- scalastyle-test-config.xml
[SASS-3588](https://jira.tools.tax.service.gov.uk/browse/SASS-3588)
> SASS-3588 StateBenefits for 2023-24 Get All State Benefits API#1938.

- app/connectors/IFConnector.scala
- app/connectors/IntegrationFrameworkConnector.scala
- conf/application.conf
- it/connectors/IntegrationFrameworkConnectorISpec.scala
- test/connectors/IFConnectorSpec.scala
[SASS-3589](https://jira.tools.tax.service.gov.uk/browse/SASS-3589)
> SASS-3589 - Implement State benefits for 2023-24 Delete API #1796

- app/config/AppConfig.scala
- app/connectors/DESConnector.scala
- app/connectors/DataExchangeServiceConnector.scala
- app/connectors/IntegrationFrameworkConnector.scala
- app/connectors/responses/DeleteStateBenefitDetailOverrideResponse.scala
- conf/application.conf
- it/connectors/DataExchangeServiceConnectorISpec.scala
- it/connectors/IntegrationFrameworkConnectorISpec.scala
- project/AppDependencies.scala
- test/connectors/DESConnectorSpec.scala
- test/connectors/responses/DeleteStateBenefitDetailOverrideResponseSpec.scala
- test/support/stubs/AppConfigStub.scala
[SASS-4338](https://jira.tools.tax.service.gov.uk/browse/SASS-4338)
> SASS-4338 - Implement 'Delete State Benefit detail override' API #1653.

- it/connectors/IntegrationFrameworkConnectorISpec.scala
> [NO-TICKET] Fix test failures caused by new tax year

- app/connectors/IntegrationFrameworkConnector.scala
- it/test/connectors/IntegrationFrameworkConnectorISpec.scala
> SASS-8041: add tax year specific changes

- conf/application.conf
> Fix staging config issue

- app/connectors/IntegrationFrameworkConnector.scala
- conf/application.conf
- it/test/connectors/IntegrationFrameworkConnectorISpec.scala
> SASS-8260:  Create Tax Year specific implementation for 1700 => 1945 state-benefits

- app/connectors/IntegrationFrameworkConnector.scala
- conf/application.conf
- it/test/connectors/IntegrationFrameworkConnectorISpec.scala
> SASS-8257: fix tax year specific api 1944

- app/connectors/IntegrationFrameworkConnector.scala
- app/services/IntegrationFrameworkService.scala
- app/services/StateBenefitsService.scala
- it/test/connectors/IntegrationFrameworkConnectorISpec.scala
- test/services/IntegrationFrameworkServiceSpec.scala
- test/services/StateBenefitsServiceSpec.scala
- test/support/mocks/MockIntegrationFrameworkConnector.scala
- test/support/mocks/MockIntegrationFrameworkService.scala
> SASS-8272: Add IF APIs 1653 & 1796

- app/config/AppConfig.scala
- app/services/CommonTaskListService.scala
- conf/application.conf
- project/plugins.sbt
- test/services/CommonTaskListServiceFixture.scala
- test/services/CommonTaskListServiceSpec.scala
- test/support/stubs/AppConfigStub.scala
> SASS-10502

- app/actions/AuthorisedAction.scala
- app/config/AppConfig.scala
- app/config/Module.scala
- app/models/User.scala
- app/models/authorisation/Enrolment.scala
- conf/application.conf
- test/actions/AuthorisedActionSpec.scala
- test/support/mocks/MockAuthorisedAction.scala
- test/support/stubs/AppConfigStub.scala
- **SASS-10602: Add new EMA feature switch config. Update app config to use trait -> class implementation**
- **SASS-10602: Add EMA functionality and associated testing changes.**
> SASS 10602

- app/actions/AuthorisedAction.scala
- test/actions/AuthorisedActionSpec.scala
> Fix to handle non auth errors

- app/actions/AuthorisedAction.scala
- app/config/AppConfig.scala
- app/models/User.scala
- app/models/authorisation/Enrolment.scala
- build.sbt
- check.sh
- conf/application.conf
- project/AppDependencies.scala
- project/plugins.sbt
- test/actions/AuthorisedActionSpec.scala
- test/support/mocks/MockAuthorisedAction.scala
- Dependency + plugins updated
- Tests updated
- EMA disabled
> SASS-11307: EMA disabled

- README.md
- test/services/CommonTaskListServiceSpec.scala
Updated README
[SASS-11930](https://jira.tools.tax.service.gov.uk/browse/SASS-11930)
> SASS-11930 - [state-benefits] Check readme and update if needed

- project/AppDependencies.scala
- project/plugins.sbt
> MIPR-1976: TEAM B - Upgrade dependencies
